# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_user', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='alumnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(max_length=11)),
                ('nombre', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=15)),
                ('carrera', models.CharField(max_length=100)),
                ('cuatrimestre', models.IntegerField(max_length=11)),
                ('realizado', models.IntegerField(default=0, max_length=11)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='carreras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('abrev_carrera', models.CharField(max_length=10)),
                ('jefe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='grupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_grupo', models.CharField(max_length=10)),
                ('carrera', models.CharField(max_length=100)),
                ('cuatrimestre', models.IntegerField(default=0, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='materias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('calificaciones', models.IntegerField(default=0, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='tutores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('num_grupo', models.CharField(max_length=10)),
                ('carrera', models.CharField(max_length=100)),
                ('cuatrimestre', models.IntegerField(default=0, max_length=11)),
                ('calificacion', models.IntegerField(default=0, max_length=11)),
                ('cantidad', models.IntegerField(default=0, max_length=11)),
                ('promedio', models.IntegerField(default=0, max_length=11)),
            ],
        ),
    ]
