# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='cuatrimestre',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='matricula',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='realizado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grupos',
            name='cuatrimestre',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='calificaciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutores',
            name='calificacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutores',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutores',
            name='cuatrimestre',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutores',
            name='promedio',
            field=models.IntegerField(default=0),
        ),
    ]
