# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160320_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalago',
            name='Descripcion',
            field=models.CharField(max_length=100, verbose_name=b'Descripci\xc3\xb3n'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='Descripcion',
            field=models.CharField(max_length=600, verbose_name=b'Descripci\xc3\xb3n'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='Descripcion',
            field=models.CharField(max_length=100, verbose_name=b'Descripci\xc3\xb3n'),
        ),
    ]
