# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160320_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='Clave',
            field=models.CharField(max_length=600, null=True, verbose_name=b'Clave'),
        ),
    ]
