# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_pregunta_clave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='Clave',
        ),
    ]
