# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_pregunta_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciones',
            name='Catalogo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Catalago'),
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='Materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Materia'),
        ),
        migrations.AddField(
            model_name='catalago',
            name='EvaluacionSencilla',
            field=models.BooleanField(default=False, verbose_name=b'Evaluaci\xc3\xb3n sencilla'),
        ),
    ]
