# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 01:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160324_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comentario', models.CharField(max_length=500)),
                ('Alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='Carrera',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='Grupo',
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='Tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Tutor'),
        ),
        migrations.AddField(
            model_name='catalago',
            name='alumnos',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='Catalogo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Catalago'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='Periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Periodo'),
        ),
    ]
