# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160328_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='Grupos',
        ),
        migrations.AddField(
            model_name='maestro',
            name='Grupos',
            field=models.ManyToManyField(to='main.Grupo'),
        ),
    ]
