# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20160407_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrera',
            options={'ordering': ['Nombre']},
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['Cuatrimestre']},
        ),
        migrations.AlterModelOptions(
            name='jefecarrera',
            options={'ordering': ['Nombre']},
        ),
        migrations.AlterModelOptions(
            name='maestro',
            options={'ordering': ['Nombre']},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['Carrera', 'Nombre']},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'ordering': ['Maestro']},
        ),
    ]
