# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20160409_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciones',
            name='Grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Grupo'),
        ),
    ]
